<section id="one">
	<div class="inner">
		<header class="major">
			<p>Titre : <strong><?php print($this->entries[0]->title); ?></strong> </p>
		</header>
		<p>Contenu : <strong><?php print($this->entries[0]->content); ?></strong> </p>


		<p>Date : <strong><?php print($this->entries[0]->date); ?></strong> </p>
	</div>

	<hr class="major">


	<div class="row 200%">
		<div class="6u 12u$(medium)">

			<h4>Les derniers commentaires</h4>
			<div class="table-wrapper">
				<table class="alt">
					<thead>
					<tr>
						<th>Description</th>
						<th>Date</th>
					</tr>
					</thead>
					<tbody>


					<?php foreach ($this->entries_comment as $entry):

						if($entry->newsid == $this->entries[0]->id):?>

							<tr>
								<td><?php echo $this->escape($entry->content); ?></td>

								<td><?php echo $this->escape($entry->date); ?></td>
							</tr>
						<?php endif; ?>

					<?php endforeach; ?>



					</tbody>

				</table>
			</div>

		</div>

		<div class="6u 12u$(medium)">

			<h3>Ajouter un commentaire</h3>

			<?php
			if(isset($this-> form))
				echo $this-> form;
			?>
		</div>


	</div>

</section>




