
<div class="row 200%">
	<div class="6u 12u$(medium)">

		<div id="view-content">

			<div class="content table-responsive table-full-width">
				<table class="table table-hover table-striped">
					<thead>
					<tr>
						<td>Titre</td>
						<td>Contenu</td>
						<td>Date</td>
						<td>Suppression</td>
						<td>Créer par </td>
					</tr>
					</thead>
					<tbody>
					<?php foreach ($this->entries_news as $entry): ?>
						<tr>
							<td>
								<a href="<?php echo $this->url(array('controller'=>'news','action'=> 'find'),'default',true)."?news=".$this->escape($entry->id);?>">
									<?php echo $this->escape($entry->title);?> </a>
							</td>
							<td><?php echo $this->escape($entry->content); ?></td>
							<td><?php echo $this->escape($entry->date); ?></td>

							<td><a href="<?php echo $this->url(array('controller'=>'news','action'=> 'delete'),'default',true)."?news=".$this->escape($entry->id);?>">
									Supprimé </a> </td>
							<td>

								<?php foreach ($this->entries_user as $entry_user):
									if( $entry->userid == $entry_user->id )
										echo $this->escape($entry_user->name);
								endforeach;
								if($entry->userid == 0 ){
									echo  'Anonyme';
								}

								?>

							</td>
						</tr>
					<?php endforeach ?>
					</tbody>

				</table>
			</div>

		</div>

	</div>

</div>

<div class="6u$ 12u$(medium)">

	<ul class="actions">
		<li>
			<a href="<?php echo $this->url(array('controller'=>'news','action'=> 'add'),'default',true);?>" class="button special big fa-pencil-square">Créér une acutalité</a>
		</li>
	</ul>


</div>





