
<div class="row 200%">
	<div class="6u 12u$(medium)">

		<div id="view-content">


		<div class="content table-responsive table-full-width">
		<table class="table table-hover table-striped">
			<thead>
			<tr>
				<td>Photo</td>
				<td>Nom</td>
				<td>Email</td>
			</tr>
			</thead>
			<tbody>
			<?php foreach ($this->entries as $entry): ?>
				<tr>

					<td>
					<?php if($entry->pathimg!=null): ?>
						<img style="width: 100px;margin-left: 20px; margin-right: 20px;" src="/public/img/<?php echo $this->escape($entry->pathimg) ?>" />
					<?php else:  ?>

					<ul class="icons">
						<li>	<a class="alt icon fa-user" href="#"></a></li>
					</ul>
					</td>

					<?php endif; ?>



					<td>
						<a href="<?php echo $this->url(array('controller'=>'user','action'=> 'find'),'default',true)."?user=".$this->escape($entry->id);?>" > <?php print $this->escape($entry->name) ?></a>
					</td>



					<td><?php echo $this->escape($entry->email); ?></td>
				</tr>
			<?php endforeach ?>
			</tbody>

		</table>
	</div>

</div>
