<div id="view-content">
	<div class="content table-responsive table-full-width">
		<table class="table table-hover table-striped">
		<thead>
		<tr>
			<td>Id</td>
			<td>Titre</td>
			<td>Contenu</td>
			<td>Date</td>
			<td>Suppression</td>
			<td>Créer par </td>
		</tr>
		</thead>
		<tbody>
		<?php foreach ($this->entries_news as $entry): ?>
			<tr>

				<td><?php echo $this->escape($entry->id); ?></td>
				<td>
					<a href="<?php echo $this->url(array('controller'=>'news','action'=> 'find'),'default',true)."?news=".$this->escape($entry->id);?>">
						<?php echo $this->escape($entry->title);?> </a>
				</td>
				<td><?php echo $this->controller->substrwords($this->escape($entry->content),10); ?></td>
				<td><?php echo $this->escape($entry->date); ?></td>

				<td><a href="<?php echo $this->url(array('controller'=>'news','action'=> 'delete'),'default',true)."?news=".$this->escape($entry->id);?>">
						Supprimé </a> </td>
				<td>

					<?php foreach ($this->entries_user as $entry_user):
						if( $entry->userid == $entry_user->id )
							echo $this->escape($entry_user->name);
					endforeach;
					if($entry->userid == 0 ){
						echo  'Anonyme';
					}

					?>

				</td>
			</tr>
		<?php endforeach ?>
		</tbody>

	</table>
</div>
</div>