
<?php

 $this->headTitle()->prepend("Page d'accueil");
    echo $this->headTitle();




 ?>



<section id="banner" class="major">
    <div class="inner">
        <header class="major">
            <h1>Bienvenue sur notre reseau socialy</h1>
        </header>
        <div class="content">
            <p>A responsive site template designed by HTML5 UP<br />
                and released under the Creative Commons.</p>
        </div>
    </div>
</section>





<div id="contact">
 <!--   <?php
/*
    if(isset($this->isconnected)){

        if(isset($this->name))

            echo        'Salut  '.$this->name; */?>

        <br/>
        <?php /* if(isset($this->email))

            echo 'Votre email est  '.$this->email; */?>


        <a href="/login/logout"> Se déconnecte </a>

    <?php /*} else  { */?>

        <a href="register">Inscrivez-ous</a>

        <br/>

        <span> Ou </span>

        <br/>

        <a class="icon fa-login" href="FormLogin">Connectez-vous</a>

    --><?php /*} */?>

</div>


