<section id="contact">
	<div class="inner">
		<section>
			<?php
			if(isset($this-> form))
				echo $this-> form;
			?>
		</section>
		<section class="split">
			<section>
				<div class="contact-method">
					<span class="icon alt fa-envelope"></span>
					<h3>Email</h3>
					<a href="#">information@untitled.tld</a>
				</div>
			</section>
			<section>
				<div class="contact-method">
					<span class="icon alt fa-phone"></span>
					<h3>Phone</h3>
					<span>(000) 000-0000 x12387</span>
				</div>
			</section>
			<section>
				<div class="contact-method">
					<span class="icon alt fa-home"></span>
					<h3>Address</h3>
										<span>1234 Somewhere Road #5432<br>
										Nashville, TN 00000<br>
										United States of America</span>
				</div>
			</section>
		</section>
	</div>
</section>
