<br /><br />
<div id="view-content" ng-controller="myCtrl_update" ng-init="displayUser()" >

	<div  >
		<dl class="zend_form">

			<dt id="id-label" style="display: none;">

				<label for="id" ">id</label>

			</dt>

			<dd id="id-element" style="display: none;">
				<input type="text" name="id"  value="{{user.id}}"  ng-model="user.id" />

			</dd>

			<dt id="email-label">

				<label for="email" >Email</label>

			</dt>

			<dd id="email-element">

				<input type="text"   ng-model="user.email" />

			</dd>

			<dt id="login-label">

				<label for="login" >Login</label>

			</dt>

			<dd id="login-element">

				<input type="text" ng-model="user.name" />

			</dd>

			<dt id="password-label">

				<label for="password" >Mot de pass</label>

			</dt>

			<dd id="password-element">

				<input type="password"  ng-model="user.password" />

			</dd>



			<dd id="Modifier-element">
				<button ng-click="updateData();">Modifier</button></dd>
		</dl>

	</div>



	<div >

		<!--<table  >

			<tr ng-repeat="x in data1" >


				<td>{{ x.id }} | {{ x.name }} | {{ x.email }} | </td>

			</tr>

		</table>-->

	</div>




</div>




